// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Infra.Data.Context;

namespace webapi.Infra.Data.Migrations
{
    [DbContext(typeof(KeyCenterContext))]
    partial class KeyCenterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("webapi.Domain.Models.KeyObject", b =>
                {
                    b.Property<int>("IdKey")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("KeyClosedTimestamp");

                    b.Property<string>("KeyGroup");

                    b.Property<string>("KeyRelease");

                    b.Property<DateTime?>("KeyUsedTimestamp");

                    b.Property<string>("KeyValue");

                    b.HasKey("IdKey");

                    b.ToTable("RegisteredKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
